# Numpy (Week 1-lesson1)
 
- one of the core packages for numerical computing in python
- many packages are built on top of numpy
- numpy has been optimized for processing: 
    faster memory access


In [3]:
# import numpy with standard abbreviation

import numpy as np

## Variables 

we can think about variables as a name we assign to particular object in python 

For example:

In [4]:
# assign a small array to a variable a 

a = np.array( [ [1,1,2], [3, 5, 8], ] )

when we run the cell we store the variable and its value. we can see the variables value in two ways:

In [5]:
a

array([[1, 1, 2],
       [3, 5, 8]])

In [6]:
print(a) #usually displays it nicer

[[1 1 2]
 [3 5 8]]


## Naming variables
in the class we are going to use 'snake_case' for naming variable.

## Variables and objects
**objects**: often encouraged in python documentation and tutorials

object is a bundle of properties and actions of something specific

Example:

- objects: data frame 
- properties: number of rows, names of columns, data created
- actions: selecting a row, adding a column 

A variable is a name we give a specific object, and the same object can be referenced by different variables

Example: 
- The sun (actual star at the center of our solar system = object 
- sol = Spanish word for sun = variable 
- soleil = french for sun = another variable

In practice: we will use object and variable interchangeably

## Types 

Each object in python has a type 

type = what kind of object it is 

We can call the type of the object, the **classes** of the object 

We can see the type/class of an object by using the **type** function

In [7]:
print(a)
type(a)

[[1 1 2]
 [3 5 8]]


numpy.ndarray

The **numpy.ndarray** is the core object/data type in the NumPy package. We can check the type of an entry in the array by indexing:

In [8]:
print(a[0,0]) #picking the first column in first row
type(a[0,0])

1


numpy.int64

In [10]:
# how would you access the value of 5 in array a?

print(a[1, 1])

5


## Functions 

'print' was a our example of a python function! :) 

A function: 
- take in a set of **arguments**, separated by commas, and 
- use those arguments to produce some **output**

argument = parameter : you might argument more often in the documentation 

We can ask information about a function by executing **?** followed by the function name: 

In [11]:
?print

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


- first line: function showing all of its arguments in paranthesis 
- then a short description of what the function does 
- finally, a list of the arguments and a brief explanation of each of them.

Different types of arguments inside the paranthesis. 
Roughly speaking, there are two types of arguments:

- **non-optional arguments**: arguments you need to specify for the function to do something 
- **optional arguments**: arguments that are pre filled with a default value by its function, but we can override them. optional arguments inside the paranthesis () in the form.

'optional arguments = default_ value'


# Attributes and Methods (Week1- lesson2)

An object in python has attributes and methods.

-**attributes**: a property of an object, a piece of information about it.

-**method**: a procedure associated with an object, an action where the main ingredient is object itself 

Access a variable attributes and methods by adding a period '.' at the end of the variable's name.

***'variable.variable_method()'*** or 
***'variable.variable_attribute'***

Examples: 
Methods and attributes of NumPy arrays.

In [3]:
#define a 3x3 array
import numpy as np

var = np.array( [ [1,2,3], [4,5,6], [7,8,9] ] )
var

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
#shape: attribute tell us the number of elements in each dimension of the array
var.shape

(3, 3)

In [5]:
type(var.shape)

tuple

In [7]:
#ndim is an attribute holding the number of array dimensions 
var.ndim
type(var.ndim)

int

Noticed attributes can have many different data types

Examples of methods: 

In [9]:
#min method for the array (return the min value in array too)

var.min()

type(var.min)

builtin_function_or_method

## R & Python

R: 
- doesn't use methods within an object
- functions in R are extrinsic to (outside) the objects they are acting on 

Examples: recreate getting the min value in an array

In R there would be two separate items: the variable "var" and a *separate* function 'min' that gets 'var' as a parameter 

#this is r code 

var <- array(c(2,3,45,6,67,7,7), dim=c(3,3)
min(var)


Using the pype operator >%> in R's tidyverse is closer to the '.' in python:

var <- array(c(2,3,45,6,67,7,7), dim=c(3,3)
var >%> min()

What is happening?
The pipe '>%>' is passing 'var' to the 'min()' as its first argument. This is essentially what the period does in python:


